// Generated by eXtraCoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define('calendar', ['console', 'lib/jquery-ui.custom.min', 'lib/fullcalendar.min'], function(_arg) {
    var CalendarFrameView, FrameView, find;
    find = _arg.find, FrameView = _arg.FrameView;
    CalendarFrameView = (function(_super) {

      __extends(CalendarFrameView, _super);

      function CalendarFrameView() {
        return CalendarFrameView.__super__.constructor.apply(this, arguments);
      }

      CalendarFrameView.prototype.initialize = function(options) {
        CalendarFrameView.__super__.initialize.call(this, options);
        this.sidebarListEl = find('.sidebar-list', this.el);
      };

      CalendarFrameView.prototype.render = function() {
        var autoResize, container, r, viewEl,
          _this = this;
        $('#calendar_view', this.el).fullCalendar({
          header: {
            left: "prev,next today",
            center: "title",
            right: "month,agendaWeek,agendaDay"
          },
          editable: true
        });
        viewEl = find('#calendar_view', this.el);
        container = viewEl.parentNode;
        r = 800 / 645;
        autoResize = function() {
          var h, w;
          w = container.clientWidth;
          h = container.clientHeight;
          if (w / h < r) {
            viewEl.style.width = '100%';
          } else {
            viewEl.style.width = Math.floor(h * r) - 20 + 'px';
          }
        };
        $(window).resize(autoResize).resize();
      };

      return CalendarFrameView;

    })(FrameView);
    return CalendarFrameView;
  });

}).call(this);

/*
//@ sourceMappingURL=calendar.map
*/
