// Generated by eXtraCoffeeScript 1.6.1
(function() {

  require(['console'], function(_arg) {
    var ConsoleView, Router, SignInView, app;
    ConsoleView = _arg.ConsoleView, SignInView = _arg.SignInView, Router = _arg.Router;
    window.app = app = {
      console: ConsoleView.get(),
      signin: SignInView.get(),
      router: Router.get()
    };
    Backbone.history.start();
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
