// Generated by eXtraCoffeeScript 1.6.1
(function() {

  require(['console'], function(_arg) {
    var ConsoleView, Router, SignInView, app;
    ConsoleView = _arg.ConsoleView, SignInView = _arg.SignInView, Router = _arg.Router;
    window.app = app = {
      console: new ConsoleView,
      signin: new SignInView,
      router: new Router
    };
    app.signin.on('success', function() {
      this.hide();
      app.console.$el.show();
    });
    app.signin.trigger('success');
    app.router.console = app.console;
    Backbone.history.start();
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
