// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  define('crypto', ['lib/crypto-js'], function(CryptoJS) {
    var COMMON_SALT;
    COMMON_SALT = 'MARXO';
    return {
      hashPassword: function(email, password) {
        var hash, salt;
        salt = CryptoJS.algo.HMAC.create(CryptoJS.algo.SHA256, COMMON_SALT).update(email).finalize();
        hash = CryptoJS.PBKDF2(password, salt, {
          hasher: CryptoJS.algo.SHA256,
          keySize: 256 / 32,
          iterations: 256
        });
        hash = hash.toString(CryptoJS.enc.Base64);
        return hash.slice(0, -1);
      },
      md5Email: function(email) {
        return CryptoJS.MD5(email).toString(CryptoJS.enc.Hex);
      }
    };
  });

}).call(this);
