#!/bin/bash
cd "$(dirname "$(which $0)")" > /dev/null

echo 'copy libs'
rm -rf out/js
mkdir -p out/js/lib/test
cp js/lib/*.js out/js/lib/
cp js/lib/test/*.js out/js/lib/test/

echo 'js/models.coffee + js/console.coffee + js/manager.coffee + js/main.coffee -> out/js/main.js'
coffee -pjc js/models.coffee js/console.coffee js/manager.coffee js/main.coffee \
 | uglifyjs - -o out/js/main.js -mc --screw-ie8

for coffee in js/*.coffee ; do
    [[ -f "$coffee" ]] || continue
    #[[ "$coffee" == "js/test_data.coffee" ]] && continue
    [[ "$coffee" == "js/manager.coffee" || "$coffee" == "js/models.coffee" || "$coffee" == "js/console.coffee" || "$coffee" == "js/main.coffee" ]] && continue
    js="out/js/$(basename -s .coffee $coffee).js"
    echo "$coffee -> $js"
    coffee -cp "$coffee" | uglifyjs - -o "$js" -mc --screw-ie8
done

echo 'compile less to out/css/console.css'
rm out/css/console.css
lessc --no-ie-compat --yui-compress -O2 css/console.less out/css/console.css

echo 'compile jade to out/index.html'
rm out/index.html
jade -D -p . index.jade -o out/

echo 'copy other resources'
rm -rf out/img out/font
cp -r img out/
cp -r font out/

cd - > /dev/null
